-- 0005: Daily Active Users pre-aggregate table.
-- Populated by recomputeDailyDau() after each indexer pass. Mirrors Dune
-- query 6974179: DAU = COUNT(DISTINCT addr) across (Deposited, WithdrawalExecuted,
-- Reserved, ChannelSettled, ChannelClosed) × (buyer, seller where applicable).
-- new_users = count of buyers whose first lifetime Deposited event is on this day.
-- Drizzle-kit's autogenerated rebase noise has been stripped; only the
-- additive parts remain so this migration is safe to re-run.

CREATE TABLE IF NOT EXISTS "daily_dau" (
	"day" date PRIMARY KEY NOT NULL,
	"dau" integer DEFAULT 0 NOT NULL,
	"dau_buyers" integer DEFAULT 0 NOT NULL,
	"dau_sellers" integer DEFAULT 0 NOT NULL,
	"new_users" integer DEFAULT 0 NOT NULL,
	"last_recomputed_at" bigint
);
