// Fixed-window rate limiter using in-process Maps.
// Works for single-instance deployments (dev, Vercel Fluid Compute reuse).
// Limits are soft on multi-instance — still bounds any one instance.

import { db } from "./db";
import { apiKeys } from "./schema";
import { eq } from "drizzle-orm";

const FREE_LIMIT = 60;    // req/min, no key
const KEY_LIMIT = 300;    // req/min, validated API key
const WINDOW_MS = 60_000;

interface Bucket {
  count: number;
  windowStart: number;
}

const buckets = new Map<string, Bucket>();

// In-process cache of validated keys (avoids a DB hit on every request).
const validKeyCache = new Map<string, number>(); // key → validUntil timestamp
const KEY_CACHE_TTL = 60_000;

function check(id: string, limit: number): { allowed: boolean; retryAfter: number } {
  const now = Date.now();
  const bucket = buckets.get(id);

  if (!bucket || now - bucket.windowStart >= WINDOW_MS) {
    buckets.set(id, { count: 1, windowStart: now });
    return { allowed: true, retryAfter: 0 };
  }

  if (bucket.count >= limit) {
    const retryAfter = Math.ceil((WINDOW_MS - (now - bucket.windowStart)) / 1000);
    return { allowed: false, retryAfter };
  }

  bucket.count += 1;
  return { allowed: true, retryAfter: 0 };
}

// Prune stale buckets to prevent unbounded growth (runs at most once/minute).
let lastPrune = 0;
function maybePrune() {
  const now = Date.now();
  if (now - lastPrune < WINDOW_MS) return;
  lastPrune = now;
  for (const [id, bucket] of buckets) {
    if (now - bucket.windowStart >= WINDOW_MS * 2) buckets.delete(id);
  }
  // Prune stale key cache entries too.
  for (const [key, validUntil] of validKeyCache) {
    if (Date.now() > validUntil) validKeyCache.delete(key);
  }
}

async function isValidApiKey(raw: string): Promise<boolean> {
  // Shape check: keys are 64 hex chars generated by randomBytes(32).
  if (!/^[0-9a-f]{64}$/i.test(raw)) return false;
  const cached = validKeyCache.get(raw);
  if (cached && Date.now() < cached) return true;
  try {
    const rows = await db.select({ key: apiKeys.key }).from(apiKeys).where(eq(apiKeys.key, raw)).limit(1);
    if (rows.length > 0) {
      validKeyCache.set(raw, Date.now() + KEY_CACHE_TTL);
      return true;
    }
  } catch {
    // DB unavailable — fall back to free tier rather than crashing.
  }
  return false;
}

export async function checkRateLimit(
  ip: string,
  apiKey: string | null,
): Promise<{ allowed: boolean; retryAfter: number }> {
  maybePrune();
  if (apiKey && (await isValidApiKey(apiKey))) {
    return check(`key:${apiKey}`, KEY_LIMIT);
  }
  return check(`ip:${ip}`, FREE_LIMIT);
}

export function getClientIp(req: Request): string {
  // Prefer x-real-ip (set by Vercel edge directly to the client IP).
  const realIp = req.headers.get("x-real-ip");
  if (realIp) return realIp.trim();
  // Fall back to XFF — read the LAST entry, which is what Vercel appends.
  const xff = req.headers.get("x-forwarded-for");
  if (xff) {
    const parts = xff.split(",").map((s) => s.trim()).filter(Boolean);
    if (parts.length > 0) return parts[parts.length - 1];
  }
  return "unknown";
}
