// Fixed-window rate limiter. Primary path uses Neon/rate_limit_buckets atomic
// counters so limits hold across serverless instances; in-process buckets are
// retained as a DB-unavailable fallback.

import { db } from "./db";
import { apiKeys, rateLimitBuckets } from "./schema";
import { eq, sql } from "drizzle-orm";
import { hashApiKey, hashIdentifier, isApiKeyShape } from "./apiKeys";

const FREE_LIMIT = 60;    // req/min, no key
const KEY_LIMIT = 300;    // req/min, validated API key
const WINDOW_MS = 60_000;
const SHARED_BUCKET_PREFIX = "rate:v1";

interface Bucket {
  count: number;
  windowStart: number;
}

const buckets = new Map<string, Bucket>();

// In-process cache of validated key hashes (avoids a DB hit on every request
// without retaining raw API keys in memory longer than the current call).
const validKeyCache = new Map<string, number>(); // hash → validUntil timestamp
const invalidKeyCache = new Map<string, number>(); // hash → invalidUntil timestamp
const KEY_CACHE_TTL = 60_000;
const NEGATIVE_KEY_CACHE_TTL = 10_000;

function check(id: string, limit: number): { allowed: boolean; retryAfter: number } {
  const now = Date.now();
  const bucket = buckets.get(id);

  if (!bucket || now - bucket.windowStart >= WINDOW_MS) {
    buckets.set(id, { count: 1, windowStart: now });
    return { allowed: true, retryAfter: 0 };
  }

  if (bucket.count >= limit) {
    const retryAfter = Math.ceil((WINDOW_MS - (now - bucket.windowStart)) / 1000);
    return { allowed: false, retryAfter };
  }

  bucket.count += 1;
  return { allowed: true, retryAfter: 0 };
}

// Prune stale buckets to prevent unbounded growth (runs at most once/minute).
let lastLocalPrune = 0;
let lastSharedPrune = 0;
function maybePruneLocal() {
  const now = Date.now();
  if (now - lastLocalPrune < WINDOW_MS) return;
  lastLocalPrune = now;
  for (const [id, bucket] of buckets) {
    if (now - bucket.windowStart >= WINDOW_MS * 2) buckets.delete(id);
  }
  // Prune stale key cache entries too.
  for (const [key, validUntil] of validKeyCache) {
    if (Date.now() > validUntil) validKeyCache.delete(key);
  }
  for (const [key, invalidUntil] of invalidKeyCache) {
    if (Date.now() > invalidUntil) invalidKeyCache.delete(key);
  }
}

async function maybePruneSharedBuckets() {
  const now = Date.now();
  if (now - lastSharedPrune < WINDOW_MS) return;
  lastSharedPrune = now;
  const cutoffWindow = Math.floor((now - WINDOW_MS * 2) / WINDOW_MS) * WINDOW_MS;
  try {
    await db.execute(sql`
      DELETE FROM rate_limit_buckets
      WHERE window_start < ${cutoffWindow}
    `);
  } catch {
    // Non-fatal; stale buckets are small rows and the next request can retry.
  }
}

async function checkShared(
  kind: "ip" | "key",
  id: string,
  limit: number,
): Promise<{ allowed: boolean; retryAfter: number } | null> {
  const now = Date.now();
  const windowStart = Math.floor(now / WINDOW_MS) * WINDOW_MS;
  const retryAfter = Math.max(1, Math.ceil((WINDOW_MS - (now - windowStart)) / 1000));
  const bucketKey = `${SHARED_BUCKET_PREFIX}:${kind}:${hashIdentifier(id)}:${windowStart}`;
  try {
    await maybePruneSharedBuckets();
    const r = await db
      .insert(rateLimitBuckets)
      .values({ bucketKey, count: 1, windowStart })
      .onConflictDoUpdate({
        target: rateLimitBuckets.bucketKey,
        set: { count: sql`${rateLimitBuckets.count} + 1` },
      })
      .returning({ count: rateLimitBuckets.count });
    const count = Number(r[0]?.count ?? 0);
    if (!Number.isFinite(count) || count <= 0) return null;
    return { allowed: count <= limit, retryAfter: count <= limit ? 0 : retryAfter };
  } catch {
    return null;
  }
}

async function validateApiKey(raw: string): Promise<string | null> {
  // Shape check: keys are 64 hex chars generated by randomBytes(32).
  if (!isApiKeyShape(raw)) return null;
  const keyHash = hashApiKey(raw);
  const now = Date.now();
  const cached = validKeyCache.get(keyHash);
  if (cached && now < cached) return keyHash;
  const invalidCached = invalidKeyCache.get(keyHash);
  if (invalidCached && now < invalidCached) return null;
  try {
    const rows = await db.select({ key: apiKeys.key }).from(apiKeys).where(eq(apiKeys.key, keyHash)).limit(1);
    if (rows.length > 0) {
      validKeyCache.set(keyHash, now + KEY_CACHE_TTL);
      return keyHash;
    }

    // One-way migration for legacy plaintext rows: first successful use
    // rewrites the primary key to the hash and never returns the raw value.
    const legacyRows = await db.select({ key: apiKeys.key }).from(apiKeys).where(eq(apiKeys.key, raw)).limit(1);
    if (legacyRows.length > 0) {
      await db.update(apiKeys).set({ key: keyHash }).where(eq(apiKeys.key, raw));
      validKeyCache.set(keyHash, now + KEY_CACHE_TTL);
      return keyHash;
    }
  } catch {
    // DB unavailable — fall back to free tier rather than crashing.
  }
  invalidKeyCache.set(keyHash, now + NEGATIVE_KEY_CACHE_TTL);
  return null;
}

export async function checkRateLimit(
  ip: string,
  apiKey: string | null,
): Promise<{ allowed: boolean; retryAfter: number }> {
  maybePruneLocal();
  const keyHash = apiKey ? await validateApiKey(apiKey) : null;
  if (keyHash) {
    return (await checkShared("key", keyHash, KEY_LIMIT)) ?? check(`key:${keyHash}`, KEY_LIMIT);
  }
  return (await checkShared("ip", ip, FREE_LIMIT)) ?? check(`ip:${ip}`, FREE_LIMIT);
}

export function getClientIp(req: Request): string {
  // Trust x-real-ip only on Vercel, where the platform edge owns this header.
  // In local/self-hosted contexts a caller can spoof it, so collapse anonymous
  // traffic into the shared unknown bucket instead.
  const realIp = req.headers.get("x-real-ip");
  if (process.env.VERCEL === "1" && realIp) return realIp.trim();
  // Do not trust raw X-Forwarded-For when the platform-trusted header is absent.
  return "unknown";
}
